theme: jekyll-theme-cayman
title: Esqueixada
description: Website d'esqueixada, un projecte obert amb la missió de difondre la importància i l'impacte de tecnologies i sistemes que promouen la descentralització.
repository: Esqueixada/web
exclude: [docker-compose.yml]
github: [metadata]
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"